Repository Pick-Point/PickPoint, pull requests merged in 2025-02, with the labels that each got.

#12 [UI, DOCS] NumberSettingComponent 구현, PR template 추가
  .github/pull_request_template.md
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/NumberSettingComponent.kt
  app/src/main/res/drawable/ic_number_setting_minus.xml
Labels: UI, Docs

#14 [feat]: Setting Component 구현 (#7)
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/SettingComponent.kt
  app/src/main/res/drawable/ic_setting_check_24.xml
Labels: UI

#17 [FEAT, REFACTOR] 앱 테마별 색상 사용 기능 구현
  app/src/main/java/com/pickpoint/pickpoint/ui/theme/AppTheme.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/theme/Color.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/theme/PointColors.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/theme/Theme.kt
Labels: Feat, Refactor

#20 [Feat] Setting 정보를 내부 데이터에 저장하는 기능을 구현한다.
  app/build.gradle.kts
  app/src/main/java/com/pickpoint/pickpoint/MainActivity.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/SettingComponent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/util/DataStoreManager.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/home/screen/FakeSettingScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/home/viewmodel/HomeViewModelFactory.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/model/setting/LanguageSetting.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/model/setting/PreferencesSetting.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/model/setting/ThemeSetting.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: Feat

#18 [FEAT]: Color, Font 사용 환경 구축
  .github/pull_request_template.md
  app/build.gradle.kts
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/ThemeDemoComponent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/util/Utils.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/theme/Color.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/theme/Theme.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/theme/Type.kt
  app/src/main/res/values/font-cert.xml
  gradle/libs.versions.toml
Labels: Feat

#26 [FEAT] Random Picker 화면 로직 구현
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/Point.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/game/RandomPickerGameComponent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/util/TimerStartHandler.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/util/Utils.kt
Labels: Feat, Refactor

#31 [FEAT] RandomPicker 리팩토링, TeamMaker 구현
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/Point.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/util/TimerStartHandler.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/randompicker/component/RandomPickerGameComponent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/teammaker/component/TeamMakerGameComponent.kt
Labels: Feat, Refactor

#33 [FEAT] what to do 컴포넌트 작성
  app/src/main/java/com/pickpoint/pickpoint/ui/whattodo/component/WTDGameComponent.kt
Labels: Feat

#36 [FEAT] 게임 컴포넌트 화면 연결
  app/build.gradle.kts
  app/src/main/java/com/pickpoint/pickpoint/navigation/PickPointNavGraph.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/common/component/PickPointTopAppBars.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/randompicker/component/RandomPickerSettingComponent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/randompicker/screen/RandomPickerScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/randompicker/screen/RandomPickerSettingScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/teammaker/component/TeamMakerSettingContent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/teammaker/component/TeamMakerTryAgain.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/teammaker/screen/TeamMakerScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/teammaker/screen/TeamMakerSettingScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/whattodo/component/WTDSeeResult.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/whattodo/screen/WhatToDoScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/whattodo/viewmodel/WhatToDoViewmodel.kt
Labels: Feat
