Repository Pick-Point/PickPoint, pull requests merged in 2025-08, with the labels that each got.

#63 [FIX] WTD 화면 버그 수정 , 카운트 시작까지 시간 축소
  app/src/main/java/com/pickpoint/pickpoint/ui/common/util/TimerStartHandler.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/randompicker/component/RandomPickerGameComponent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/teammaker/component/TeamMakerGameComponent.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/whattodo/component/WTDGameComponent.kt
Labels: Fix

#65 [REFACTOR] WTD 화면에서의 레이아웃 리팩토링, 언어 설정 변경시 팝업으로 확인 받기
  app/src/main/java/com/pickpoint/pickpoint/ui/home/screen/SettingScreen.kt
  app/src/main/java/com/pickpoint/pickpoint/ui/whattodo/screen/WhatToDoScreen.kt
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: Fix, Refactor, Merge OK

#67 [update]: 1.4.0 update
  app/build.gradle.kts
Labels: version update
